[workflow]
# CPG-flow requires an input cohort to start up, a dataset to run as, and a permission level
# usually these would be populated by analysis-runner
dataset = 'dataset_name'
access_level = 'test'  # or 'standard'

sequencing_type = 'genome'

# an input cohort is required to get cpg-flow to run
input_cohorts = ['COHXYZ']

# used to make sure we don't repeat previously completed stages
check_expected_outputs = true

# if you want to screen out any ClinVar submitters when re-summarising, add them to this list
# example use cases would be blinding an analysis to your own clinvar submissions
site_blacklist = []

# genome build, required for bcftools annotation and Hail setup
# currently only GRCh37 and GRCh38 are supported (including bundled GFF3 files for annotation)
genome_build = 'GRCh38'
