name: Run pre-commit hooks
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: requirements*.txt

    - name: Install packages
      run: pip install .[test]

    - name: Install pre-commit hooks
      run: pre-commit install --install-hooks

    - name: Run pre-commit
      run: pre-commit run --all-files
